import './globals.css'
import { DM_Sans } from 'next/font/google'
import { Metadata } from "next"

const font = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400']
})

export const metadata: Metadata = {
  title: 'Zanna Du',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-black ${font.className}`}>
        {children}
        {/* Cloudflare Web Analytics zannaduband.com */}
        <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "219323fc33984841ae8d442c62b9e6cd"}' />
        {/* Cloudflare Web Analytics: zannadu.band */}
        <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "b0d24829b92143979b0108659e4efbbe"}' />
      </body>
    </html>
  )
}
